export type JobCategoryType =
    | ""
    | "외식/음료"
    | "매장/판매"
    | "생산-건설"
    | "생산-기술"
    | "사무/영업"
    | "문화/여가/생활"
    | "농어촌/선원"
    | "모델/쇼핑몰"
    | "교육"
    | "기타/서비스"

export type  EducationType = "학력무관" | "고졸" | "대학생" | "대학 졸업 및 졸업예정자" | "대학원생" | "대학원 졸업 및 졸업예정자"
export type VisaType = "D-2" | "D-4" | "C-3"
